---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: finished-webhook
  annotations:
    thoth-station.ninja/template-version: 0.7.0
  labels:
    app: thoth
    component: finished-webhook
spec:
  templates:
    - name: finished-webhook
      inputs:
        parameters:
          - name: "THOTH_WORKFLOW_NAME"
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_ADVISER_METADATA"
          - name: "IMAGE_STREAM_REGISTRY"
          - name: "IMAGE_STREAM_NAMESPACE"
          - name: "IMAGE_STREAM_TAG"
      container:
        name: trigger-finished-webhook
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/\
        {{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/\
        workflow-helpers:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        env:
          - name: THOTH_WORKFLOW_TASK
            value: "trigger_integration"
          - name: THOTH_WORKFLOW_NAME
            value: "{{inputs.parameters.WORKFLOW_NAME}}"
          - name: THOTH_DOCUMENT_ID
            value: "{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: THOTH_ADVISER_METADATA
            value: "{{inputs.parameters.THOTH_ADVISER_METADATA}}"
          - name: "WEBHOOK_CALLBACK_URL"
            value: "http://qeb-hwt-aicoe-prod-bots.cloud.paas.psi.redhat.com"
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_SECRET
                name: qeb-hwt-github-app
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
